datasets:
  - name: plutonic_1
    dataset_description: 'all node and edge features binned'
    save_root: /scratch/lllang/crystal_gen/Graph_Network_Project/data/processed/datasets
    raw_root: /scratch/lllang/crystal_gen/Graph_Network_Project/data/raw/test
    n_cores: 40
    node_features:
      - name: 'verts_neighbor_angles_encodings'
        params: {'n_bins':100,'min_val':0, 'max_val':(3/2)*np.pi, 'sigma':0.1}
      - name: 'verts_neighbor_areas_encodings'
        params: {'n_bins':100,'min_val':0, 'max_val':3, 'sigma':0.1}
    edge_index:
      - name: 'verts_edge_index'
    edge_features: 
      - name: 'verts_neighbor_distance'
        params: {'do_encoding':True, 'n_bins':100,'min_val':0, 'max_val':3, 'sigma':0.1 }
    y_feature: 
      - name: 'verts_energy_per_node'
        params: {}

  - name: nelement_max_3_nsites_max_10_3d_1
    dataset_description: 'all node and edge features binned'
    save_root: /scratch/lllang/crystal_gen/Graph_Network_Project/data/processed/datasets
    raw_root: /scratch/lllang/crystal_gen/Graph_Network_Project/data/raw/nelement_max_3_nsites_max_10_3d
    n_cores: 40
    node_features:
      - name: 'verts_neighbor_angles_encodings'
        params: {'n_bins':100,'min_val':0, 'max_val':(3/2)*np.pi, 'sigma':0.1}
      - name: 'verts_neighbor_areas_encodings'
        params: {'n_bins':100,'min_val':0, 'max_val':3, 'sigma':0.1}
    edge_index:
      - name: 'verts_edge_index'
    edge_features: 
      - name: 'verts_neighbor_distance'
        params: {'do_encoding':True, 'n_bins':100,'min_val':0, 'max_val':3, 'sigma':0.1 }
    y_feature: 
      - name: 'verts_energy_per_node'
        params: {}

  - name: plutonic_2
    dataset_description: 'all node features binned, edge feature continuous'
    save_root: /scratch/lllang/crystal_gen/Graph_Network_Project/data/processed/datasets
    raw_root: /scratch/lllang/crystal_gen/Graph_Network_Project/data/raw/test
    n_cores: 40
    node_features:
      - name: 'verts_neighbor_angles_encodings'
        params: {'n_bins':100,'min_val':0, 'max_val':(3/2)*np.pi, 'sigma':0.1}
      - name: 'verts_neighbor_areas_encodings'
        params: {'n_bins':100,'min_val':0, 'max_val':3, 'sigma':0.1}
    edge_index:
      - name: 'verts_edge_index'
    edge_features: 
      - name: 'verts_neighbor_distance'
        params: {'do_encoding':False, 'n_bins':100,'min_val':0, 'max_val':3, 'sigma':0.1 }
    y_feature: 
      - name: 'verts_energy_per_node'
        params: {}

  - name: nelement_max_3_nsites_max_10_3d_2
    dataset_description: 'all node features binned, edge feature continuous'
    save_root: /scratch/lllang/crystal_gen/Graph_Network_Project/data/processed/datasets
    raw_root: /scratch/lllang/crystal_gen/Graph_Network_Project/data/raw/nelement_max_3_nsites_max_10_3d
    n_cores: 40
    node_features:
      - name: 'verts_neighbor_angles_encodings'
        params: {'n_bins':100,'min_val':0, 'max_val':(3/2)*np.pi, 'sigma':0.1}
      - name: 'verts_neighbor_areas_encodings'
        params: {'n_bins':100,'min_val':0, 'max_val':3, 'sigma':0.1}
    edge_index:
      - name: 'verts_edge_index'
    edge_features: 
      - name: 'verts_neighbor_distance'
        params: {'do_encoding':False, 'n_bins':100,'min_val':0, 'max_val':3, 'sigma':0.1 }
    y_feature: 
      - name: 'verts_energy_per_node'
        params: {}